---

- name: Install Required OS Packages
  package:
    name: cronie
    state: present

- name: Install Pip Packages
  pip:
    name: datadog
    version: 0.40.1

- name: disk-usage script
  copy:
    src: datadog-docker-disk-usage.py
    dest: /usr/local/bin/
    mode: 0755

- name: disk-usage cron
  cron:
    name: disk-usage-cron
    user: root
    job: "/usr/local/bin/datadog-docker-disk-usage.py &>> /var/log/datadog-docker-disk-usage.log"
    cron_file: datadog-docker-disk-usage

- name: Add datadog key
  cronvar:
    name: DATADOG_API_KEY
    value: "%DATADOG_API_KEY_TEMPLATE%"
    cron_file: datadog-docker-disk-usage
