---

- name: Install Required OS Packages
  package:
    name: cronie
    state: present

- name: Install Pip Packages
  pip:
    name: datadog

- name: disk-usage script
  copy:
    src: datadog-docker-disk-usage.py
    dest: /usr/local/bin/
    mode: 0755

- name: disk-usage cron
  cron:
    name: disk-usage-cron
    user: root
    job: "/usr/local/bin/datadog-docker-disk-usage.py &>> /var/log/datadog-docker-disk-usage.log"
    cron_file: datadog-docker-disk-usage

- name: Add datadog key
  cronvar:
    name: DATADOG_API_KEY
    value: "%DATADOG_API_KEY_TEMPLATE%"
    cron_file: datadog-docker-disk-usage

- name: docker config file dir
  file:
    name: /etc/datadog-agent/conf.d/docker.d/
    state: directory

- name: docker config file
  copy:
    src: docker_conf.yaml
    dest: /etc/datadog-agent/conf.d/docker.d/conf.yaml

- name: httpd config file dir
  file:
    name: /etc/datadog-agent/conf.d/httpd.d/
    state: directory

- name: httpd config file
  copy:
    src: httpd_conf.yaml
    dest: /etc/datadog-agent/conf.d/httpd.d/conf.yaml

- name: jmx config file dir
  file:
    name: /etc/datadog-agent/conf.d/jmx.d/
    state: directory

- name: jmx config file
  copy:
    src: jmx_conf.yaml
    dest: /etc/datadog-agent/conf.d/jmx.d/conf.yaml

- name: pull image
  docker_image:
    name: datadog/agent:latest-jmx
