---

- name: Install Required OS Packages
  ansible.builtin.dnf:
    name: cronie
    state: present


- name: Install setuptools
  ansible.builtin.dnf:
    name:
      - python
      - python-setuptools
      - pip
      - gzip
      - unzip
      - tar
      - git
      - lvm2

- name: Install pinned ver of Decorator Pip Package
  ansible.builtin.pip:
    name: decorator
    version: 4.4.2

- name: Install Datadog Pip Package
  ansible.builtin.pip:
    name: datadog

- name: Disk-usage script
  ansible.builtin.copy:
    src: datadog-docker-disk-usage.py
    dest: /usr/local/bin/
    mode: 0755

- name: Disk-usage cron
  ansible.builtin.cron:
    name: disk-usage-cron
    user: root
    job: "/usr/local/bin/datadog-docker-disk-usage.py &>> /var/log/datadog-docker-disk-usage.log"
    cron_file: datadog-docker-disk-usage

- name: Add datadog key
  community.general.cronvar:
    name: DATADOG_API_KEY
    value: "%DATADOG_API_KEY_TEMPLATE%"
    cron_file: datadog-docker-disk-usage
