---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: centos_image
    image: centos:7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
