---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: public.ecr.aws/docker/library/fedora:latest
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    # - idempotence
    - lint
    - verify
verifier:
  name: testinfra
