---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
  safe_files:
    - /usr/local/bin/datadog-docker-disk-usage.py
lint:
  name: yamllint
platforms:
  - name: centos_image
    image: centos:7
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    hosts: 'docker://centos_image'
  lint:
    name: flake8
